# Generated by Django 6.0 on 2025-12-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_trainer_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancersAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField(default=list)),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_availabilities', to='main.dancer')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_availabilities', to='main.day')),
            ],
        ),
    ]
