# Generated by Django 6.0 on 2025-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_dancersavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
