# Generated by Django 6.0 on 2025-12-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_group_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='primary',
        ),
    ]
