# Generated by Django 6.0 on 2025-12-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_group_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_lessons', to='main.group'),
        ),
    ]
